name: Test Cases

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test Cases
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test Cases
      run: cargo test --release